Repository reviewpad/action, pull requests merged in 2022-08, with the labels that each got.

#18 fix: update go build to properly assign mixpanel token
  agent/runners.go
  main.go
Labels: medium, critical

#22 feat: add exit status to reviewpad runners
  agent/runners.go
Labels: critical, small

#20 feat/input_configuration_file_url
  .gitignore
  action.yml
  agent/runners.go
  go.mod
  go.sum
  main.go
  utils/url.go
  utils/url_test.go
Labels: medium, large, external-contribution, critical

#24 chore: update reviewpad and host event handler dependencies
  agent/runners.go
  go.mod
  go.sum
  utils/file.go
Labels: medium, critical

#28 Add banner to README.md
  README.md
Labels: external-contribution, small

#30 feat: support for issues
  agent/runners.go
  go.mod
  go.sum
Labels: large, critical

#31 ReadMe Updated With Necessary Formatting
  README.md
Labels: external-contribution, small
