Repository reviewpad/action, pull requests merged in 2022-09, with the labels that each got.

#38 feat: add libgit2 installation to dockerfile
  Dockerfile
Labels: small

#40 fix: fail action when GitHub API calls fail
  agent/runners.go
Labels: critical, small, show

#44 fix: schedule event not handled
  agent/runners.go
Labels: critical, small
